#!/bin/bash -le

debug() {
  echo "::debug::$*"
}

error() {
  echo "::error::$*"
}

fatal() {
  error "$*"
  exit 1
}

group() {
  echo "::group::$*"
}

endgroup() {
  echo "::endgroup::"
}

group 'setup'

builddir=build
test_install=0

pacman -Syu --noconfirm base-devel cmake python git powertop ttf-nerd-fonts-symbols
# Add after the existing pacman install line
if [ "$1" = "coverage" ]; then
    pacman -S --noconfirm lcov
    cmake_flags="-DENABLE_COVERAGE=ON"
fi


# Needed to ensure PATH is properly set for perl, etc.
source /etc/profile

endgroup

# build
group 'build'
cmake -B "$builddir" \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  ${cmake_flags}
cmake --build "$builddir"
endgroup

# test, excluding changelog tests
group 'test'
cd "$builddir" && ctest --output-on-failure
# After running tests, generate coverage if enabled
if [ "$1" = "coverage" ]; then
    lcov --capture --directory . --output-file coverage.info
    lcov --remove coverage.info '/usr/*' --output-file coverage.info
fi
endgroup



# install
if (( test_install )); then
  group 'install'
  cmake --install . --config RelWithDebInfo 
  endgroup
fi