name: arch.x86_64
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        
        container:
            image: archlinux
        
        steps:
            - uses: actions/checkout@v4
            - run: build-aux/ci-test coverage
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  file: ./build/coverage.info
        